/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ResumeDraftRouteImport } from "./routes/resume.draft";
import { Route as AuthedDashboardRouteImport } from "./routes/_authed/dashboard";
import { Route as AuthedResumeIdRouteImport } from "./routes/_authed/resume.$id";
import { ServerRoute as AuthedGeneratePdfServerRouteImport } from "./routes/_authed/generate.pdf";

const rootServerRouteImport = createServerRootRoute();

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ResumeDraftRoute = ResumeDraftRouteImport.update({
  id: "/resume/draft",
  path: "/resume/draft",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedResumeIdRoute = AuthedResumeIdRouteImport.update({
  id: "/resume/$id",
  path: "/resume/$id",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedGeneratePdfServerRoute = AuthedGeneratePdfServerRouteImport.update({
  id: "/_authed/generate/pdf",
  path: "/generate/pdf",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/dashboard": typeof AuthedDashboardRoute;
  "/resume/draft": typeof ResumeDraftRoute;
  "/resume/$id": typeof AuthedResumeIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/dashboard": typeof AuthedDashboardRoute;
  "/resume/draft": typeof ResumeDraftRoute;
  "/resume/$id": typeof AuthedResumeIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/_authed/dashboard": typeof AuthedDashboardRoute;
  "/resume/draft": typeof ResumeDraftRoute;
  "/_authed/resume/$id": typeof AuthedResumeIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/sign-in"
    | "/sign-up"
    | "/dashboard"
    | "/resume/draft"
    | "/resume/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/sign-in"
    | "/sign-up"
    | "/dashboard"
    | "/resume/draft"
    | "/resume/$id";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/sign-in"
    | "/sign-up"
    | "/_authed/dashboard"
    | "/resume/draft"
    | "/_authed/resume/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
  ResumeDraftRoute: typeof ResumeDraftRoute;
}
export interface FileServerRoutesByFullPath {
  "/generate/pdf": typeof AuthedGeneratePdfServerRoute;
}
export interface FileServerRoutesByTo {
  "/generate/pdf": typeof AuthedGeneratePdfServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/_authed/generate/pdf": typeof AuthedGeneratePdfServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/generate/pdf";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/generate/pdf";
  id: "__root__" | "/_authed/generate/pdf";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  AuthedGeneratePdfServerRoute: typeof AuthedGeneratePdfServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/resume/draft": {
      id: "/resume/draft";
      path: "/resume/draft";
      fullPath: "/resume/draft";
      preLoaderRoute: typeof ResumeDraftRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/dashboard": {
      id: "/_authed/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthedDashboardRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/resume/$id": {
      id: "/_authed/resume/$id";
      path: "/resume/$id";
      fullPath: "/resume/$id";
      preLoaderRoute: typeof AuthedResumeIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/_authed/generate/pdf": {
      id: "/_authed/generate/pdf";
      path: "/generate/pdf";
      fullPath: "/generate/pdf";
      preLoaderRoute: typeof AuthedGeneratePdfServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute;
  AuthedResumeIdRoute: typeof AuthedResumeIdRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedResumeIdRoute: AuthedResumeIdRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ResumeDraftRoute: ResumeDraftRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthedGeneratePdfServerRoute: AuthedGeneratePdfServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
